### PR TITLE
Dynamodb

### PR DESCRIPTION
**Pull request by brenopessoa**
Hello, I tried implemented this driver, is missing the document support ,
but  will start work on it as soon as I can.
Any kind of feedback are welcome. Thanks

Adds support to DynamoDB #21

### CODE REVIEW

**Comment by genie-jnosql** [comment]
Can one of the admins verify this patch?

**Comment by otaviojava** [comment]
@brenopessoa please, update the header to 2018

**Comment by brenopessoa** [comment]
Uupdate the header to 2018 done , 
Thanks for the feedback.

**Comment by keilw** [comment]
@ulich Wanna help?

**Comment by ulich** [comment]
yeah, but whats the status? :) without having looked at the diff, it sounds like its all done and someone just needs to merge

**Comment by otaviojava** [comment]
Thank you

**Comment by brenopessoa** [comment]
thank's for the merge.
I'm in debt with a document driver, but i'll try soon.

**Comment by otaviojava** [comment]
Ok, I'll take a look also :)

**Comment by otaviojava** [comment]
@brenopessoa could you take a look?
```
[INFO] org.jnosql.diana:dynamodb-driver 0.0.7-SNAPSHOT .... FAILURE [  0.806 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:08 min
[INFO] Finished at: 2019-02-04T01:06:14-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project dynamodb-driver: Compilation failure: Compilation failure: 
[ERROR] /jobs/genie.jnosql/jnosql-diana-driver/workspace/dynamodb-driver/src/main/java/org/jnosql/diana/dynamodb/DynamoDBBuilderASync.java:[25,45] software.amazon.awssdk.http.nio.netty.NettyNioAsyncHttpClient is not public in software.amazon.awssdk.http.nio.netty; cannot be accessed from outside package
[ERROR] /jobs/genie.jnosql/jnosql-diana-driver/workspace/dynamodb-driver/src/main/java/org/jnosql/diana/dynamodb/DynamoDBBuilderASync.java:[34,46] package NettyNioAsyncHttpClient does not exist
[ERROR] /jobs/genie.jnosql/jnosql-diana-driver/workspace/dynamodb-driver/src/main/java/org/jnosql/diana/dynamodb/DynamoTableUtils.java:[17,1] cannot find symbol
[ERROR]   symbol:   static KEY
[ERROR]   location: interface
[ERROR] /jobs/genie.jnosql/jnosql-diana-driver/workspace/dynamodb-driver/src/main/java/org/jnosql/diana/dynamodb/key/DynamoDBBucketManager.java:[17,1] cannot find symbol
[ERROR]   symbol:   static VALUE
[ERROR]   location: interface
[ERROR] /jobs/genie.jnosql/jnosql-diana-driver/workspace/dynamodb-driver/src/main/java/org/jnosql/diana/dynamodb/DynamoDBUtils.java:[18,1] cannot find symbol
[ERROR]   symbol:   static VALUE
[ERROR]   location: interface
[ERROR] /jobs/genie.jnosql/jnosql-diana-driver/workspace/dynamodb-driver/src/main/java/org/jnosql/diana/dynamodb/DynamoDBUtils.java:[17,1] cannot find symbol
[ERROR]   symbol:   static KEY
[ERROR]   location: interface
[ERROR] /jobs/genie.jnosql/jnosql-diana-driver/workspace/dynamodb-driver/src/main/java/org/jnosql/diana/dynamodb/DynamoDBUtils.java:[55,43] cannot find symbol
[ERROR]   symbol:   variable VALUE
[ERROR]   location: class org.jnosql.diana.dynamodb.DynamoDBUtils
[ERROR] /jobs/genie.jnosql/jnosql-diana-driver/workspace/dynamodb-driver/src/main/java/org/jnosql/diana/dynamodb/DynamoDBUtils.java:[63,25] cannot find symbol
[ERROR]   symbol:   variable KEY
[ERROR]   location: class org.jnosql.diana.dynamodb.DynamoDBUtils
[ERROR] /jobs/genie.jnosql/jnosql-diana-driver/workspace/dynamodb-driver/src/main/java/org/jnosql/diana/dynamodb/DynamoDBUtils.java:[119,92] cannot find symbol
[ERROR]   symbol:   variable KEY
[ERROR]   location: class org.jnosql.diana.dynamodb.DynamoDBUtils
[ERROR] /jobs/genie.jnosql/jnosql-diana-driver/workspace/dynamodb-driver/src/main/java/org/jnosql/diana/dynamodb/key/DynamoDBBucketManager.java:[93,58] cannot find symbol
[ERROR]   symbol:   variable VALUE
[ERROR]   location: class org.jnosql.diana.dynamodb.key.DynamoDBBucketManager
[ERROR] /jobs/genie.jnosql/jnosql-diana-driver/workspace/dynamodb-driver/src/main/java/org/jnosql/diana/dynamodb/DynamoDBBuilderASync.java:[34,68] cannot find symbol
[ERROR]   symbol:   variable NettyNioAsyncHttpClient
[ERROR]   location: class org.jnosql.diana.dynamodb.DynamoDBBuilderASync
[ERROR] /jobs/genie.jnosql/jnosql-diana-driver/workspace/dynamodb-driver/src/main/java/org/jnosql/diana/dynamodb/DynamoDBBuilderSync.java:[34,107] cannot access software.amazon.awssdk.http.SdkHttpClientFactory
[ERROR]   class file for software.amazon.awssdk.http.SdkHttpClientFactory not found
[ERROR] /jobs/genie.jnosql/jnosql-diana-driver/workspace/dynamodb-driver/src/main/java/org/jnosql/diana/dynamodb/DynamoTableUtils.java:[86,49] cannot find symbol
[ERROR]   symbol:   variable KEY
[ERROR]   location: class org.jnosql.diana.dynamodb.DynamoTableUtils
[ERROR] /jobs/genie.jnosql/jnosql-diana-driver/workspace/dynamodb-driver/src/main/java/org/jnosql/diana/dynamodb/DynamoTableUtils.java:[90,49] cannot find symbol
[ERROR]   symbol:   variable KEY
[ERROR]   location: class org.jnosql.diana.dynamodb.DynamoTableUtils
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :dynamodb-driver
Build step 'Invoke top-level Maven targets' marked build as failure
Sending e-mails to: otaviopolianasantana@gmail.com lucasfurlaneto.s@gmail.com
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: FAILURE
```

**Comment by otaviojava** [comment]
Hey @brenopessoa I'll just remove from the parent, Also it will be amazing if you update it to use the newest API:
https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-dynamodb/1.11.490

**Comment by otaviojava** [comment]
https://github.com/eclipse/jnosql-diana-driver/issues/112

**Comment by brenopessoa** [comment]
Yes , i'll can look it.

**Comment by otaviojava** [comment]
btw, I commented the dynamodb to make green at the build:

https://github.com/eclipse/jnosql-diana-driver/commit/e66383a51c33da6f63f81ab94e497b8cf7dac31c

Please, don't forget to return it.

**Comment by amoscatelli** [comment]
@brenopessoa @otaviojava any update ? I can work on it if you need help.
I will update the aws driver and fix the problem.
Should I make a new pull request ?

**Comment by keilw** [comment]
@amoscatelli Do you have a valid ECA in place?

**Comment by amoscatelli** [comment]
@keilw sorry, I didn't know anything about ECA till now.
Going to find out about it.
Meanwhile I made the pull request:
https://github.com/eclipse/jnosql-communication-driver/pull/166

**Comment by amoscatelli** [comment]
Hi again guys.
I want to mention that a Document Driver is still missing.

Atm I can't handle this but if nobody else will I will make an attempt later.

And the KeyValue Driver doesn't support polymorphism. For this, I believe, we need JsonB to fully support polymorphism and we'll have to wait for the current refactor that will be ready for Jakarta 10 both in spec and RI (they told me so).

**Comment by amoscatelli** [comment]
@otaviojava I am going to work on the Document driver soon

**Comment by otaviojava** [comment]
@amoscatelli 
Thank you!

**Pull request merged**
