### PR TITLE
Support to define a file properties to MongoDB 

### PR DESCRIPTION
**Pull request by rhuan080**
Created a new method to MongoDBDocumentConfiguration to allow define another file properties to config the access to MongoDB. 
Then we can define the file properties with this line: 
configuration.get("jnosql-config.properties");

### CODE REVIEW

**Comment by genie-jnosql** [comment]
Can one of the admins verify this patch?

**Comment by leomrlima** [comment]
Why do you touch so many drivers from other databases, if this is related to MongoDB?

**Comment by leomrlima** [comment]
Why are there so many changes on so many files?
`File Changes
M .gitignore (0)
M CONTRIBUTING.md (0)
M LICENSE.md (0)
M README.md (0)
M arangodb-driver/README.md (0)
M arangodb-driver/pom.xml (0)`

**Comment by rhuan080** [comment]
Would you like that I create a new pull request?

**Comment by otaviojava** [comment]
Hey, @rhuan080  do you mind to create a new PR just with these three files?

**Pull request closed without merging**
