### PR TITLE
Created a constant to mongo server prefix.

### PR DESCRIPTION
**Pull request by rhuan080**
Created a constant called PREFIX_SERVER_HOST to mongo server prefix.

### CODE REVIEW

**Comment by genie-jnosql** [comment]
Can one of the admins verify this patch?

**Comment by keilw** [comment]
@rhuan080 The problem is, 
>ip-validation — The pull request did not pass Eclipse validation. The following users have invalid Signed-off-by footers: rhuan080@gmail.com 

Did you just miss that in your PR or are you missing an ECA, too?

**Comment by rhuan080** [comment]
Hi,

Can you explain to me how can I resolve that?

**Comment by Daniel-Dos** [comment]
Hi @rhuan080 ,

You need to have ECA signed -> (https://www.eclipse.org/legal/ECA.php) .

**Comment by otaviojava** [comment]
Thank you @rhuan080 let us know when you fix the ECA

**Comment by rhuan080** [comment]
Done!

**Comment by rhuan080** [comment]
Do I need to make a new pull request?

**Comment by otaviojava** [comment]
Please, try to create a new one

**Comment by otaviojava** [comment]
Thank you

**Comment by rhuan080** [comment]
Thanks!

**Pull request merged**
