### PR TITLE
change json concrete dependence to JSONValueProvider in redis collect…

### PR DESCRIPTION
**Pull request by brenopessoa**
Please, check it's make sense.

### CODE REVIEW

**Comment by otaviojava** [comment]
Hello Breno.
Thanks.
That makes sense.
I'll just run the test to check if that is ok.

**Comment by otaviojava** [comment]
Hey @brenopessoa  did you check the tests:

```java
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/otaviojava/Environment/code/workspace-jnosql/jnosql-diana-driver/redis-driver/src/main/java/org/jnosql/diana/redis/key/RedisKeyValueEntityManagerFactory.java:[57,16] constructor RedisList in class org.jnosql.diana.redis.key.RedisList<T> cannot be applied to given types;
  required: redis.clients.jedis.Jedis,java.lang.Class<T>,java.lang.String,org.jnosql.diana.driver.value.JSONValueProvider
  found: redis.clients.jedis.Jedis,java.lang.Class<T>,java.lang.String
  reason: actual and formal argument lists differ in length
[ERROR] /home/otaviojava/Environment/code/workspace-jnosql/jnosql-diana-driver/redis-driver/src/main/java/org/jnosql/diana/redis/key/RedisKeyValueEntityManagerFactory.java:[64,16] constructor RedisSet in class org.jnosql.diana.redis.key.RedisSet<T> cannot be applied to given types;
  required: redis.clients.jedis.Jedis,java.lang.Class<T>,java.lang.String,org.jnosql.diana.driver.value.JSONValueProvider
  found: redis.clients.jedis.Jedis,java.lang.Class<T>,java.lang.String
  reason: actual and formal argument lists differ in length
[ERROR] /home/otaviojava/Environment/code/workspace-jnosql/jnosql-diana-driver/redis-driver/src/main/java/org/jnosql/diana/redis/key/RedisKeyValueEntityManagerFactory.java:[71,16] constructor RedisQueue in class org.jnosql.diana.redis.key.RedisQueue<T> cannot be applied to given types;
  required: redis.clients.jedis.Jedis,java.lang.Class<T>,java.lang.String,org.jnosql.diana.driver.value.JSONValueProvider
  found: redis.clients.jedis.Jedis,java.lang.Class<T>,java.lang.String
  reason: actual and formal argument lists differ in length
[ERROR] /home/otaviojava/Environment/code/workspace-jnosql/jnosql-diana-driver/redis-driver/src/main/java/org/jnosql/diana/redis/key/RedisKeyValueEntityManagerFactory.java:[78,16] cannot infer type arguments for org.jnosql.diana.redis.key.RedisMap<>
  reason: cannot infer type-variable(s) K,V
    (actual and formal argument lists differ in length)

```

**Comment by brenopessoa** [comment]
I have some problems with ECA eclipse.
I sign-in and accept the therms of ECA and did commit with signoff but apparently don't work
I tried ammend the commits. Sorry the mess with commits.

**Comment by keilw** [comment]
@brenopessoa Did you use the correct email here as in the ECA? There are plenty of examples especially in some Eclipse MicroProfile repositories where committers or contributors use multiple accounts and show up more than once in the commit stats ;-/

**Comment by otaviojava** [comment]
@brenopessoa did you check this https://www.eclipse.org/legal/CoO.php ?

**Comment by brenopessoa** [comment]
Hi @keilw i use the same email in both accounts.
I just update my eclipse profile with GitHub ID

**Comment by otaviojava** [comment]
@brenopessoa  , please, follow the link: https://dev.eclipse.org/eclipse-webhook/services/status_details.php?id=594a5ae0b0d03

**Comment by otaviojava** [comment]
@brenopessoa 
There is a check style issue:
```
[INFO] There are 2 errors reported by Checkstyle 6.11.2 with /home/otaviojava/Environment/code/workspace-jnosql/jnosql-diana-driver/redis-driver/target/checkstyle-rules.xml ruleset.
[ERROR] src/main/java/org/jnosql/diana/redis/key/RedisMap.java:[81,9] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
[ERROR] src/main/java/org/jnosql/diana/redis/key/RedisCollection.java:[39,5] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.378 s
[INFO] Finished at: 2017-06-21T09:14:00-03:00
[INFO] Final Memory: 29M/328M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (verify-style) on project redis-driver: You have 2 Checkstyle violations. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by brenopessoa** [comment]
Ok , initially i skip the checkstyle verification
I'll fix this. Thanks guys

**Comment by brenopessoa** [comment]
It's better concetrate the effort's in this suggestion 

https://github.com/eclipse/jnosql-diana-driver/issues/29

**Pull request closed without merging**
