### PR TITLE
Changed to MongoDBDocumentConfiguration to allow define another file properties.

### PR DESCRIPTION
**Pull request by rhuan080**
Created a new method to MongoDBDocumentConfiguration to allow define another file properties to config the access to MongoDB. 
Then we can define the file properties with this line:
              configuration.get("jnosql-config.properties");

### CODE REVIEW

**Comment by genie-jnosql** [comment]
Can one of the admins verify this patch?

**Comment by rhuan080** [comment]
Hi, why does this file has a conflict?

**Comment by Daniel-Dos** [comment]
HI, 

the file in master was mofificated .

https://github.com/eclipse/jnosql-diana-driver/blob/aeec70653e1c89e3f7c31bda748865ac49e3c87d/mongodb-driver/src/main/java/org/jnosql/diana/mongodb/document/MongoDBDocumentConfiguration.java#L106L111

try an rebase .

**Comment by rhuan080** [comment]
Thank you guys!

**Comment by otaviojava** [comment]
I'll close it, when you fix it, please, open again.
Thank for your help.

**Pull request closed without merging**
